name: Build Zed release (Windows x64, VS2022)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      # Сокращаем пути, чтобы не было ошибки "path too long"
      CARGO_HOME: C:\c
      CARGO_TARGET_DIR: C:\t

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Setup MSVC (Visual Studio 2022)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build (Release)
        run: cargo build --release

      - name: Run (Release)
        run: cargo run --release

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-app-exe
          path: C:\t\release\*.exe
